### ISSUE TITLE
Release v0.2.1.12 introduced some issues

### ISSUE THREAD

**Issue by z0zz0** [NieuwlandGeo/SLDReader#127]
Hi,

After updating from v0.2.6 to v0.2.15, I have noticed some unexpected behaviour. Which up until this moment I only can describe as unintentional behavior (error). See snippets and further comments below.

Looking at the two different images, one can see that on the v0.2.15 there are more points than there should be (compared to v0.2.6), the triangles are also different (look at the rotation). The points/circles are at different positions. v0.2.6 is showing how it should look like. I've gone through the different versions and these issues was introduced with the v0.2.12 release. Thanks :) !

## v0.2.6 running
![image](https://user-images.githubusercontent.com/44770272/170066547-9fafbbe9-e606-4f1a-8b96-f196d14fe4d2.png)

## v0.2.15 running
![image](https://user-images.githubusercontent.com/44770272/170066629-afdf65e1-71d2-4ba3-bc7e-847a1df32157.png)

**Comment by ajkopinga** [comment]
The behaviour you see in 0.2.15 is probably the correct behaviour. Previous versions did not fully conform to the SLD specification.

In particular:
* v0.2.12 fixes the problem where nothing is rendered when using a `PointSymbolizer` for polygon or line geometries. According to the SLD spec, a point should be rendered in the polygon centroid or line center, respectively.
* In older versions, `GraphicStroke` symbols were placed along the line in such a way that the vertical center line of the symbols follows along the line. This is not according to the SLD spec, which states that the horizontal center line of the image should follow the line geometry. This was fixed in v0.2.14.

Do these changes explain the behaviour you're now seeing?

**Comment by z0zz0** [comment]
Hi ajkopinga,

Yes this explains it very well. We it sorted out now. Thanks for the help and quick replies, although I can't say the same for myself.

Cheers!
