### ISSUE TITLE
Preventing overlapping of labels

### ISSUE THREAD

**Issue by lgouzin** [NieuwlandGeo/SLDReader#170]
In the [Provinces of the netherlands example](https://nieuwlandgeo.github.io/SLDReader/grenzen.html), the labels do not overlap. How is this implemented in the label rule? Is this outside the SLD? 

        <se:Rule>
          <se:TextSymbolizer>
            <se:Label>
              <ogc:PropertyName>provincienaam</ogc:PropertyName>
            </se:Label>
            <se:Font>
              <se:SvgParameter name="font-family">Noto Sans</se:SvgParameter>
              <se:SvgParameter name="font-size">13</se:SvgParameter>
            </se:Font>
            <se:LabelPlacement>
              <se:PointPlacement>
                <se:AnchorPoint>
                  <se:AnchorPointX>0.5</se:AnchorPointX>
                  <se:AnchorPointY>0.5</se:AnchorPointY>
                </se:AnchorPoint>
              </se:PointPlacement>
            </se:LabelPlacement>
            <se:Halo>
              <se:Radius>2</se:Radius>
              <se:Fill>
                <se:SvgParameter name="fill">#FFFFFF</se:SvgParameter>
              </se:Fill>
            </se:Halo>
            <se:Fill>
              <se:SvgParameter name="fill">#000000</se:SvgParameter>
            </se:Fill>
          </se:TextSymbolizer>
        </se:Rule>

**Comment by ajkopinga** [comment]
The behavior you see is the default handling of label rendering by OpenLayers. This is not caused by a specific SLD symbolizer property.

What's happening is not really related to label overlap prevention. The default behavior for polygons labeling in OpenLayers is to hide the label if it does not fit inside the polygon. That's causing the labels to disappear when you zoom out.

**Comment by lgouzin** [comment]
I see, thank you for answering. Line labels do that too indeed. 
Any recommendations for point symbology?

**Comment by ajkopinga** [comment]
There is an option you can set on a layer: `declutter:true`. I've tried that, but it prevents using a graphic and a label at the same time, since they block each other. It looks like your best bet is creating two layers: one layer for points without declutter, and one layer for the text labels with `declutter` set to `true`.

See also: https://github.com/openlayers/openlayers/issues/10849
